export const data = [
  {
    id: 1,
    name: "Flipkart",
    industry: "E-Commerce",
    location: "Bengaluru",
    employees: 30000,
    founded: 2007,
    website: "https://www.flipkart.com",
    description: "Online shopping platform.",
    revenue: "₹43,615 Cr",
    type: "Private",
  },
  {
    id: 2,
    name: "Zomato",
    industry: "Food Delivery",
    location: "Gurugram",
    employees: 5500,
    founded: 2008,
    website: "https://www.zomato.com",
    description: "Restaurant aggregator and food delivery.",
    revenue: "₹7,079 Cr",
    type: "Public",
  },
  {
    id: 3,
    name: "Byju's",
    industry: "EdTech",
    location: "Bengaluru",
    employees: 12000,
    founded: 2011,
    website: "https://www.byjus.com",
    description: "Online learning platform.",
    revenue: "₹5,014 Cr",
    type: "Private",
  },
  {
    id: 4,
    name: "Infosys",
    industry: "IT Services",
    location: "Bengaluru",
    employees: 336000,
    founded: 1981,
    website: "https://www.infosys.com",
    description: "Global IT services leader.",
    revenue: "₹1,46,767 Cr",
    type: "Public",
  },
  {
    id: 5,
    name: "Paytm",
    industry: "FinTech",
    location: "Noida",
    employees: 9000,
    founded: 2010,
    website: "https://www.paytm.com",
    description: "Digital payments ecosystem.",
    revenue: "₹8,400 Cr",
    type: "Public",
  },
  {
    id: 6,
    name: "Nykaa",
    industry: "E-Commerce",
    location: "Mumbai",
    employees: 2300,
    founded: 2012,
    website: "https://www.nykaa.com",
    description: "Beauty and fashion e-commerce.",
    revenue: "₹5,143 Cr",
    type: "Public",
  },
  {
    id: 7,
    name: "Ola",
    industry: "Mobility",
    location: "Bengaluru",
    employees: 7000,
    founded: 2010,
    website: "https://www.olacabs.com",
    description: "Cab booking and electric mobility.",
    revenue: "₹1,970 Cr",
    type: "Private",
  },
  {
    id: 8,
    name: "RedBus",
    industry: "Travel",
    location: "Bengaluru",
    employees: 1700,
    founded: 2006,
    website: "https://www.redbus.in",
    description: "Bus ticket aggregator.",
    revenue: "₹313 Cr",
    type: "Private",
  },
  {
    id: 9,
    name: "BigBasket",
    industry: "E-Grocery",
    location: "Bengaluru",
    employees: 6300,
    founded: 2011,
    website: "https://www.bigbasket.com",
    description: "Online grocery delivery.",
    revenue: "₹7,098 Cr",
    type: "Private",
  },
  {
    id: 10,
    name: "Freshworks",
    industry: "SaaS",
    location: "Chennai",
    employees: 4500,
    founded: 2010,
    website: "https://www.freshworks.com",
    description: "CRM and support software.",
    revenue: "₹3,684 Cr",
    type: "Public",
  },
  {
    id: 11,
    name: "Delhivery",
    industry: "Logistics",
    location: "Gurugram",
    employees: 7000,
    founded: 2011,
    website: "https://www.delhivery.com",
    description: "Supply chain logistics.",
    revenue: "₹7,235 Cr",
    type: "Public",
  },
  {
    id: 12,
    name: "HCL Technologies",
    industry: "IT Services",
    location: "Noida",
    employees: 210000,
    founded: 1976,
    website: "https://www.hcltech.com",
    description: "IT consulting and outsourcing.",
    revenue: "₹1,01,456 Cr",
    type: "Public",
  },
  {
    id: 13,
    name: "Reliance Jio",
    industry: "Telecom",
    location: "Mumbai",
    employees: 31500,
    founded: 2016,
    website: "https://www.jio.com",
    description: "Telecom and digital services.",
    revenue: "₹95,804 Cr",
    type: "Public",
  },
  {
    id: 14,
    name: "Swiggy",
    industry: "Food Delivery",
    location: "Bengaluru",
    employees: 8000,
    founded: 2014,
    website: "https://www.swiggy.com",
    description: "On-demand food delivery.",
    revenue: "₹5,705 Cr",
    type: "Private",
  },
  {
    id: 15,
    name: "Bharti Airtel",
    industry: "Telecom",
    location: "New Delhi",
    employees: 22000,
    founded: 1995,
    website: "https://www.airtel.in",
    description: "Telecom and broadband services.",
    revenue: "₹1,39,156 Cr",
    type: "Public",
  },
  {
    id: 16,
    name: "Myntra",
    industry: "E-Commerce",
    location: "Bengaluru",
    employees: 3500,
    founded: 2007,
    website: "https://www.myntra.com",
    description: "Fashion e-commerce.",
    revenue: "₹7,732 Cr",
    type: "Private",
  },
  {
    id: 17,
    name: "Tata Motors",
    industry: "Automobiles",
    location: "Mumbai",
    employees: 78306,
    founded: 1945,
    website: "https://www.tatamotors.com",
    description: "Automobile manufacturer.",
    revenue: "₹3,20,800 Cr",
    type: "Public",
  },
  {
    id: 18,
    name: "Godrej Properties",
    industry: "Real Estate",
    location: "Mumbai",
    employees: 1800,
    founded: 1990,
    website: "https://www.godrejproperties.com",
    description: "Real estate developer.",
    revenue: "₹2,585 Cr",
    type: "Public",
  },
  {
    id: 19,
    name: "Zerodha",
    industry: "FinTech",
    location: "Bengaluru",
    employees: 1300,
    founded: 2010,
    website: "https://www.zerodha.com",
    description: "Discount stock broker.",
    revenue: "₹2,729 Cr",
    type: "Private",
  },
  {
    id: 20,
    name: "Asian Paints",
    industry: "Manufacturing",
    location: "Mumbai",
    employees: 7600,
    founded: 1942,
    website: "https://www.asianpaints.com",
    description: "Paints and chemicals manufacturer.",
    revenue: "₹29,347 Cr",
    type: "Public",
  },
  {
    id: 21,
    name: "Vedantu",
    industry: "EdTech",
    location: "Bengaluru",
    employees: 2500,
    founded: 2014,
    website: "https://www.vedantu.com",
    description: "Online tutoring platform.",
    revenue: "₹140 Cr",
    type: "Private",
  },
  {
    id: 22,
    name: "Nestle India",
    industry: "FMCG",
    location: "Gurugram",
    employees: 7950,
    founded: 1961,
    website: "https://www.nestle.in",
    description: "Food and beverage manufacturer.",
    revenue: "₹15,144 Cr",
    type: "Public",
  },
  {
    id: 23,
    name: "Adani Wilmar",
    industry: "Agro Processing",
    location: "Ahmedabad",
    employees: 2700,
    founded: 1999,
    website: "https://www.adaniwilmar.com",
    description: "Edible oil and food processing.",
    revenue: "₹55,438 Cr",
    type: "Public",
  },
  {
    id: 24,
    name: "Dr. Reddy’s",
    industry: "Pharmaceuticals",
    location: "Hyderabad",
    employees: 21300,
    founded: 1984,
    website: "https://www.drreddys.com",
    description: "Pharma company.",
    revenue: "₹24,798 Cr",
    type: "Public",
  },
  {
    id: 25,
    name: "Biocon",
    industry: "Biotech",
    location: "Bengaluru",
    employees: 11000,
    founded: 1978,
    website: "https://www.biocon.com",
    description: "Biopharmaceutical manufacturer.",
    revenue: "₹8,250 Cr",
    type: "Public",
  },
  {
    id: 26,
    name: "Pidilite",
    industry: "Chemicals",
    location: "Mumbai",
    employees: 9000,
    founded: 1959,
    website: "https://www.pidilite.com",
    description: "Adhesives manufacturer.",
    revenue: "₹11,752 Cr",
    type: "Public",
  },
  {
    id: 27,
    name: "Tech Mahindra",
    industry: "IT Services",
    location: "Pune",
    employees: 148000,
    founded: 1986,
    website: "https://www.techmahindra.com",
    description: "IT consulting and solutions.",
    revenue: "₹53,290 Cr",
    type: "Public",
  },
  {
    id: 28,
    name: "Naukri.com",
    industry: "Employment",
    location: "Noida",
    employees: 2900,
    founded: 1997,
    website: "https://www.naukri.com",
    description: "Job search platform.",
    revenue: "₹5,543 Cr",
    type: "Public",
  },
  {
    id: 29,
    name: "BharatPe",
    industry: "FinTech",
    location: "New Delhi",
    employees: 1500,
    founded: 2018,
    website: "https://www.bharatpe.com",
    description: "Digital payments and lending.",
    revenue: "₹1,116 Cr",
    type: "Private",
  },
  {
    id: 30,
    name: "Hero MotoCorp",
    industry: "Automobiles",
    location: "New Delhi",
    employees: 9500,
    founded: 1984,
    website: "https://www.heromotocorp.com",
    description: "Motorcycle manufacturer.",
    revenue: "₹34,488 Cr",
    type: "Public",
  },
  {
    id: 31,
    name: "HDFC Bank",
    industry: "Banking",
    location: "Mumbai",
    employees: 130000,
    founded: 1994,
    website: "https://www.hdfcbank.com",
    description: "Private sector bank.",
    revenue: "₹1,76,874 Cr",
    type: "Public",
  },
  {
    id: 32,
    name: "ICICI Bank",
    industry: "Banking",
    location: "Mumbai",
    employees: 123000,
    founded: 1994,
    website: "https://www.icicibank.com",
    description: "Private sector bank.",
    revenue: "₹1,74,547 Cr",
    type: "Public",
  },
  {
    id: 33,
    name: "SBI Life Insurance",
    industry: "Insurance",
    location: "Mumbai",
    employees: 13000,
    founded: 2001,
    website: "https://www.sbilife.co.in",
    description: "Life insurance provider.",
    revenue: "₹77,610 Cr",
    type: "Public",
  },
  {
    id: 34,
    name: "Apollo Hospitals",
    industry: "Healthcare",
    location: "Chennai",
    employees: 11000,
    founded: 1983,
    website: "https://www.apollohospitals.com",
    description: "Hospital chain.",
    revenue: "₹15,250 Cr",
    type: "Public",
  },
  {
    id: 35,
    name: "Godrej Consumer",
    industry: "FMCG",
    location: "Mumbai",
    employees: 4500,
    founded: 2001,
    website: "https://www.godrejcp.com",
    description: "Consumer products manufacturer.",
    revenue: "₹12,366 Cr",
    type: "Public",
  },
  {
    id: 36,
    name: "Emcure Pharma",
    industry: "Pharma",
    location: "Pune",
    employees: 10000,
    founded: 1981,
    website: "https://www.emcure.com",
    description: "Pharma products manufacturer.",
    revenue: "₹5,290 Cr",
    type: "Private",
  },
  {
    id: 37,
    name: "Urban Company",
    industry: "Services",
    location: "Gurugram",
    employees: 4000,
    founded: 2014,
    website: "https://www.urbancompany.com",
    description: "Home services platform.",
    revenue: "₹465 Cr",
    type: "Private",
  },
  {
    id: 38,
    name: "Lenskart",
    industry: "Retail",
    location: "Faridabad",
    employees: 4500,
    founded: 2010,
    website: "https://www.lenskart.com",
    description: "Eyewear retailer.",
    revenue: "₹1,500 Cr",
    type: "Private",
  },
  {
    id: 39,
    name: "Tata Steel",
    industry: "Manufacturing",
    location: "Mumbai",
    employees: 58000,
    founded: 1907,
    website: "https://www.tatasteel.com",
    description: "Steel manufacturer.",
    revenue: "₹2,43,431 Cr",
    type: "Public",
  },
  {
    id: 40,
    name: "Pepperfry",
    industry: "E-Commerce",
    location: "Mumbai",
    employees: 1200,
    founded: 2011,
    website: "https://www.pepperfry.com",
    description: "Online furniture retailer.",
    revenue: "₹247 Cr",
    type: "Private",
  },
  {
    id: 41,
    name: "Jubilant FoodWorks",
    industry: "Food Service",
    location: "Noida",
    employees: 8600,
    founded: 1995,
    website: "https://www.jubilantfoodworks.com",
    description: "Domino's and Dunkin' operator.",
    revenue: "₹5,156 Cr",
    type: "Public",
  },
  {
    id: 42,
    name: "Havells",
    industry: "Electricals",
    location: "Noida",
    employees: 6500,
    founded: 1958,
    website: "https://www.havells.com",
    description: "Electrical equipment manufacturer.",
    revenue: "₹16,549 Cr",
    type: "Public",
  },
  {
    id: 43,
    name: "TVS Motors",
    industry: "Automobiles",
    location: "Chennai",
    employees: 5000,
    founded: 1978,
    website: "https://www.tvsmotor.com",
    description: "Auto and two-wheeler manufacturer.",
    revenue: "₹26,381 Cr",
    type: "Public",
  },
  {
    id: 44,
    name: "Amul",
    industry: "Dairy",
    location: "Anand",
    employees: 3600,
    founded: 1946,
    website: "https://www.amul.com",
    description: "Milk and dairy product company.",
    revenue: "₹53,000 Cr",
    type: "Cooperative",
  },
  {
    id: 45,
    name: "Dabur",
    industry: "FMCG",
    location: "Ghaziabad",
    employees: 6100,
    founded: 1884,
    website: "https://www.dabur.com",
    description: "Consumer goods manufacturer.",
    revenue: "₹11,210 Cr",
    type: "Public",
  },
  {
    id: 46,
    name: "Tata Power",
    industry: "Energy",
    location: "Mumbai",
    employees: 8000,
    founded: 1911,
    website: "https://www.tatapower.com",
    description: "Power generation and distribution.",
    revenue: "₹56,984 Cr",
    type: "Public",
  },
  {
    id: 47,
    name: "Wipro",
    industry: "IT Services",
    location: "Bengaluru",
    employees: 234000,
    founded: 1945,
    website: "https://www.wipro.com",
    description: "IT consulting and outsourcing.",
    revenue: "₹90,487 Cr",
    type: "Public",
  },
  {
    id: 48,
    name: "Sun Pharma",
    industry: "Pharmaceuticals",
    location: "Mumbai",
    employees: 37000,
    founded: 1983,
    website: "https://www.sunpharma.com",
    description: "Pharma major.",
    revenue: "₹39,593 Cr",
    type: "Public",
  },
  {
    id: 49,
    name: "Faasos",
    industry: "Food Delivery",
    location: "Mumbai",
    employees: 2200,
    founded: 2011,
    website: "https://www.faasos.com",
    description: "Online food ordering and delivery.",
    revenue: "₹390 Cr",
    type: "Private",
  },
  {
    id: 50,
    name: "Suzlon Energy",
    industry: "Energy",
    location: "Pune",
    employees: 6100,
    founded: 1995,
    website: "https://www.suzlon.com",
    description: "Wind turbine manufacturer.",
    revenue: "₹5,313 Cr",
    type: "Public",
  },
];
